# SUBJECT APP CONFIG
# This is the subject application config
# store config here custom to this app and/or overrides of config in mdm-cuf-core-server.yml
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

#######################################################################################################################
# DEFAULT CONFIG
# The default config contains global configs that apply under all profiles, unless overridden (which should be rare).
#######################################################################################################################
spring: 
  profiles.include: MODE-MEMBER

# default port if running as a spring-boot app (not a deployed war) and not overriding    
server.port: 8081

# properties rendered in the /info endpoint
info.mdm-cuf-person-adapter-vha-es-server:
    version:  "@project.version@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    
# note that a /logs folder off root may be required to exist on your local to run under tomcat
logging:
  file: logs/mdm-cuf-person-adapter-vha-es-server/mdm-cuf-person-adapter-vha-es.log
     
mdm-cuf: 
  instance-subject-name: PERSON
  instance-system-name: VHA-ES
  
rest-client:
  maxConnectionsPerRoute: 2
  maxConnections: 20
  
es-service:
  apiVersion: v1
  port: 7101
  hostname: localhost
  endpoint: /contactinfo-ws/contactinf
  serviceUrl: http://localhost:7101/contactinfo-ws/contactinf
  

---
########################################################################################################################
# ENV-LOCAL-DEV PROFILE
# The default profile, used for the local dev environment.
########################################################################################################################
spring:
  profiles: ENV-LOCAL-DEV

mdm-cuf-person-adapter-vha-es:
  personBioPOST: http://localhost:7101/contactinfo-ws/contactinf
---
########################################################################################################################
# ENV-UNIT-TESTPROFILE
# Profile for UNIT Tests
########################################################################################################################
spring:
  profiles: ENV-UNIT-TEST
  profiles.include: PARTNER-SIM

mdm-cuf-person-adapter-vha-es:
  personBioPOST: http://localhost:7101/contactinfo-ws/contactinf
---
########################################################################################################################
# ENV-CI-DEV PROFILE
# Profile for the highly controlled CI env where we run all checked in code integration tests against fully controlled infrastructure
########################################################################################################################
spring:
  profiles: ENV-CI-DEV
  profiles.include: PARTNER-SIM,EMBEDDED-REDIS,CACHE-REDIS
    
mdm-cuf:
  multi-tenant-postfix: -DEV
  kafka.bootstrap-servers: kafka:9092
  cache: 
    host: localhost
    port: 
  
mdm-cuf-person-adapter-vha-es:
  personBioPOST: http://localhost:7101/contactinfo-ws/contactinf
---
########################################################################################################################
# ENV-CI-ALPHA PROFILE
# Profile for the highly controlled CI env where we run the first alpha release integration tests against fully controlled infrastructure
########################################################################################################################
spring:
  profiles: ENV-CI-ALPHA
  profiles.include: PARTNER-SIM,EMBEDDED-REDIS,CACHE-REDIS
    
mdm-cuf:
  multi-tenant-postfix: -ALPHA
  kafka.bootstrap-servers: kafka:9092 
  cache: 
    host: localhost
    port: 

